apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-worker-deployment
  labels:
    app: cron-worker
spec:
  replicas: 1 # Apenas 1 réplica para evitar tarefas duplicadas!
  selector:
    matchLabels:
      app: cron-worker
  template:
    metadata:
      labels:
        app: cron-worker
    spec:
      containers:
      - name: cron-worker
        image: k8scronworker:v1 # Nome da imagem que criamos
        imagePullPolicy: IfNotPresent # Usa a local se existir
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        #VARIÁVEIS DE AMBIENTE
        env:
        - name: CRON_SCHEDULE          # Nome da variável lida no código C#
          value: "*/1 * * * *"        # Valor: A cada 1 minuto (Minuto Hora Dia Mes DiaSemana)
        #FIM DA NOVA SEÇÃO